- name: Create a VM from a template
  hosts: localhost
  connection: local
#include variable file locations in order to retrieve the variables used in this playbook
  vars_files:
    - "~/ansible/vars.yml"
    - "~/ansible/secret/credentials.yml"
  gather_facts: no
  
  tasks:
#use of "vmware_guest" module to create new virtual machines from template and manage vm in vcenter        
    - name: Clone the template
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ vcenter_datacenter }}"
        validate_certs: False
        folder: "{{ vm_sdt_folder }}"
        state: poweredon
        name: "{{ vm_sdt_name }}"
        template: "{{ vm_sdt_template }}"
        esxi_hostname: "{{ vm_sdt_esxi_hostname }}"
        disk:
        - size_gb: "{{ vm_sdt_disk_size_gb}}"
          type: thin
          datastore: "{{ vm_sdt_datastore}}"
        hardware :
          memory_mb: "{{ vm_sdt_mem_size }}"
          num_cpus: " {{ vm_sdt_cpu_num }}"
          scsi: paravirtual
          memory_reservation_lock: "{{ vm_sdt_memory_reservation_lock }}"
          hotadd_cpu: True
          hotremove_cpu: True
          hotadd_memory: False
          boot_firmware: "efi"
        networks:
        - name: "{{ vm_sdt_network }}"
        wait_for_ip_address: True
        customization:
          hostname: "{{ vm_sdt_name }}"
      delegate_to: localhost

    
